load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
	name = "Output",
	size = "small",
	srcs = ["outputTest.cpp"],
	deps = ["//main:dstring"],
)

cc_test(
	name = "ColorPrefix",
	size = "small",
	srcs = ["colorPrefixTest.cpp"],
	deps = ["//main:dstring"],
)
