# exports_files(glob(["**/*.json"]))

filegroup(
	name = "completionData",
	srcs = glob(["completion/*.json"]),
	visibility = ["//test/Config:__pkg__"],
)

filegroup(
	name = "correctionData",
	srcs = glob(["correction/*.json"]),
	visibility = ["//test/Config:__pkg__"],
)